server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://116.62.57.216:3306/mall_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall_admin
    password: mall_2022
  redis:
    host: 116.62.57.216 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  data:
    elasticsearch:
      client:
        reactive: localhost:9200
      repositories:
        enabled: true
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  rabbitmq:
    host: localhost
    port: 15672
    virtual-host: /mall
    username: mall
    password: mall

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

# 自定义redis key
redis:
  database: mall
  expire:
    common: 86400 # 24小时
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

